# ACCEL (Evolved Curriculum via ACCEL) Hyperparameters
use_accel: true
exploratory_grad_updates: false
num_edits: 5
score_function: MaxMC
level_buffer_capacity: 4000
replay_prob: 0.8
staleness_coeff: 0.3
temperature: 0.3
topk_k: 4
minimum_fill_ratio: 0.5
prioritization: rank
buffer_duplicate_check: true
